### ISSUE TITLE
How to preventDefault?

### ISSUE THREAD

**Issue by jadiagaurang** [daybrush/keycon#4]
Hi @daybrush,

I am trying to implement Shortcuts similar to Moveable Demo ([https://daybrush.com/moveable/](https://daybrush.com/moveable/)). You must have used KeyCon to bind Keyboard Key Events. So, I have decided to use KeyCon Libary as well.

I am trying to bind `[CTRL + D]` combination to Duplicate an Element. But for some reason, it executes the Default behavior, Bookmarking!

```javascript
objKeyControllerRef = new KeyController();
me.objKeyController.keydown(["ctrl", "d"], function (event) {
    event.stop();     // Tried to Stop() to preventDefault / stopPropagation but it doesn't work!
    onElDuplicate(event);
});
```

I would appreciate any help!

**Comment by daybrush** [comment]
@jadiagaurang 

event has inputEvent.

Try calling `e.inputEvent.preventDefault()`.

Thank you :)

**Comment by jadiagaurang** [comment]
Hi @daybrush 

Thanks for providing the solution. It was very helpful to prevent default behavior!
